language: ruby
sudo: false
rvm:
- 2.3.1

cache:
  bundler: true
  cocoapods: true
  directories:
  - $HOME/.cache/pip
  - node_modules
  - $HOME/.nvm
  - $HOME/.rvm

before_install:
- gem update --system
- echo "gem version: $(gem --version)"
- echo "jekyll version: $(bundle exec jekyll --version)"
- echo "github-pages version: $(bundle exec github-pages versions)"

bundler_args: --gemfile=Gemfile --retry 3 --without test

script: "bundle exec jekyll build"

before_script:
  - git submodule init
  - git submodule update
  #- gem update github-pages
